### PR TITLE
Finishing features of cucumber calculator -  Chidi Emeh

### PR DESCRIPTION
**Pull request by Chidiemeh184**

### CODE REVIEW

**Comment by williadd** [comment]
Everything looks good.

**Comment by Chidiemeh184** [comment]
Good day'

I was trying to install Ansicon 3.1 and but it fumbled with all my command
prompt...I tried to uninstall and reinstall but I think I am missing a few
things for the cucumber and watir gems.
Please do you have office hours or any other class time during the week so
I can stop by, alternatively any instruction that I can use to get back on
track. I have been trying to get everything to
work since last night and up until now.

Regards,
Chidi Emeh

**Comment by williadd** [comment]
If I understand correctly, you uninstalled Ruby and reinstalled it?
If that is the case, make sure you installed using the RailsInstaller, not the RubyInstaller. It's a big green button for Windows, Ruby 2.0 at railsinstaller.org
When you do that, you will get a start menu item called RailsInstaller. Under that you will have an item for a command prompt with Ruby and Rails. This is the command prompt you should use to install new gems.
Place the attached Gemfile into your project directory.In the command prompt, change directory to you project directory.Run the command
    bundle install

After that you should be mostly back to a good state. If you're missing any gems at that point you can always run
    gem install somegem

from the Ruby and Rails command propmt.
As far as the ansicon gem, I would not worry about it. It only adds color output when you run cucumber.
If that doesn't help let me know and we can some up with a time this week to meet.

**Comment by williadd** [comment]
Forgot to attach the gemfile.

**Comment by Chidiemeh184** [comment]
Thanks a lot...resolved

**Pull request closed without merging**
